### ISSUE TITLE
Diferenciar bien entre el status y el newStatus

### ISSUE THREAD

**Issue by AlacranDace** [alexFocus92/juego_de_la_vida#1]
En las reglas  en el calculo de vecinos se ha de hacer en la variable "status" no sobre la "newStatus"

 # Numero de vecinos
                nNeigh = status[(x-1)%nX,(y-1)%nY] + status[(x)%nX,(y-1)%nY] + \
                        status[(x+1)%nX,(y-1)%nY] + status[(x-1)%nX,(y)%nY] + \
                        status[(x+1)%nX,(y)%nY] + status[(x-1)%nX,(y+1)%nY] + \
                         status[(x)%nX,(y+1)%nY] + status[(x+1)%nX,(y+1)%nY]

                # Rule 1: Una celula muerta con 3 vecinas revive
                if status[x,y] == 0 and nNeigh==3:
                    newStatus[x,y] = 1

                # Rule 2: Una celula viva con mas de 3 vecinos o menos de 2 muere
                elif status[x,y] == 1 and (nNeigh < 2 or nNeigh > 3):
                    newStatus[x,y] = 0

**Comment by alexFocus92** [comment]
Muchas gracias por el aporte!, lo revisaré y actualizaré.

**Comment by alexFocus92** [comment]
Solucionado! Muchas gracias de nuevo @AlacranDace .
